apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mi-pvc
      mountPath: /usr/share/nginx/html
  volumes:
  - name: mi-pvc
    persistentVolumeClaim:
      claimName: mi-pvc