apiVersion: v1 # Versión de la API de Kubernetes
kind: PersistentVolume # Tipo de objeto que estamos creando, en este caso, un PersistentVolume
metadata: # Información sobre el objeto
  name: mi-pv-nfs # Nombre de nuestro PV
  labels:
    storage: nfs # Etiqueta que se utilizará para identificar el PV
spec: # Especificaciones de nuestro PV
  capacity: # Capacidad del PV
    storage: 1Gi # 1 gigabyte de almacenamiento
  accessModes: # Modos de acceso al PV
    - ReadWriteOnce # Modo de acceso ReadWriteOnce, es decir, el PV se puede montar como lectura y escritura por un único nodo
  persistentVolumeReclaimPolicy: Retain # Política de reclamación del PV, es decir, el PV no se eliminará cuando se elimine el PVC
  nfs: # Tipo de almacenamiento que vamos a utilizar, en este caso, nfs
    server: IP_DEL_SERVIDOR_NFS # Dirección IP del servidor NFS
    path: "/mnt/nfs" # Compartición del servidor NFS
  storageClassName: nfs # Nombre de la clase de almacenamiento que se utilizará